version: '3.8'

services:
  kyc-aml-service:
    build: .
    container_name: finflow-kyc-aml-service
    ports:
      - "8005:8005"
    environment:
      AUTH_SERVICE_URL: http://host.docker.internal:8001
      PAYMENT_SERVICE_URL: http://host.docker.internal:8003
      SERVICE_PORT: 8005

networks:
  default:
    name: finflow-kyc-aml-network
